/**
 * ESLint flat config (ESLint 9+).
 *
 * Extends Next.js core-web-vitals (which includes react, react-hooks, and
 * next-specific rules) plus typescript-eslint recommended so that TypeScript
 * anti-patterns are caught at lint time rather than discovered later.
 *
 * Ignores:
 *  - .next/          — build output, never hand-written
 *  - public/sw.js    — generated by Serwist, not lintable TypeScript
 */

import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

/** @type {import("eslint").Linter.Config[]} */
const config = [
  // Ignored paths — must come first so they apply globally.
  {
    ignores: [
      ".next/**",
      "public/sw.js",
      "node_modules/**",
      "coverage/**",
      "playwright-report/**",
    ],
  },

  // next/core-web-vitals brings in next, react, react-hooks; next/typescript
  // registers the @typescript-eslint plugin + recommended TS rules (required
  // for the @typescript-eslint/* rule overrides below to resolve).
  ...compat.extends("next/core-web-vitals", "next/typescript"),

  // Project-wide overrides.
  {
    rules: {
      // Prefer named exports for better tree-shaking and refactor tooling.
      "import/prefer-default-export": "off",

      // TypeScript already enforces these; the ESLint version produces false
      // positives with generics.
      "no-undef": "off",

      // Allow underscore-prefixed vars to silence intentional "unused" params
      // (e.g. function signatures that must match an interface).
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          // Siblings of a rest element are intentionally extracted to omit
          // them (e.g. stripping queue metadata before a network payload).
          ignoreRestSiblings: true,
        },
      ],

      // Exhaustive deps is important for correctness in a data-heavy app.
      "react-hooks/exhaustive-deps": "warn",

      // Enforce consistent import ordering (cosmetic, not enforced by TS).
      // next/core-web-vitals doesn't include import plugin by default; this
      // is left as a warn to avoid blocking CI without the plugin present.
      "sort-imports": "off",
    },
  },
];

export default config;
